apiVersion: v2
name: kube-s3-operator
description: A Kubernetes operator for managing AWS S3 buckets
type: application
version: 0.2.1
appVersion: "0.2.1"
home: https://github.com/victorbecerragit/kube-s3-operator
sources:
  - https://github.com/victorbecerragit/kube-s3-operator
maintainers:
  - name: Victor Becerra
    email: vbecerraar@gmail.com
keywords:
  - kubernetes
  - operator
  - aws
  - s3
  - storage
