{{- if and .Values.awsCredentials.enabled .Values.awsCredentials.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.awsCredentials.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if .Values.awsCredentials.accessKeyId }}
  {{ .Values.awsCredentials.accessKeyIdKey }}: {{ .Values.awsCredentials.accessKeyId | b64enc }}
  {{- end }}
  {{- if .Values.awsCredentials.secretAccessKey }}
  {{ .Values.awsCredentials.secretAccessKeyKey }}: {{ .Values.awsCredentials.secretAccessKey | b64enc }}
  {{- end }}
{{- end }}
