# This rule is not used by the project code itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to s3.acme.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: code
    app.kubernetes.io/managed-by: kustomize
  name: s3bucket-viewer-role
rules:
- apiGroups:
  - s3.acme.io
  resources:
  - s3buckets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - s3.acme.io
  resources:
  - s3buckets/status
  verbs:
  - get
