apiVersion: s3.acme.io/v1alpha1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: code
    app.kubernetes.io/managed-by: kustomize
  name: my-bucket-test-acme
  namespace: s3-acme
spec:
  name: my-bucket-test-acme-2025
  region: us-west-2
  locked: false
  lifecycle:
    rules:
      - id: expire-30-days
        status: Enabled
        expiration:
          days: 30
        transitions:
          - days: 7
            storageClass: STANDARD_IA
  #accessControl: private
