apiVersion: s3.acme.io/v1alpha1
kind: S3Bucket
metadata:
  labels:
    app.kubernetes.io/name: code
    app.kubernetes.io/managed-by: kustomize
  name: s3bucket-sample
spec:
  # TODO(user): Add fields here
